---
- name: Jinja example 
  hosts: all 
  tasks: 
    - name: Template a file to /etc/hosts
      ansible.builtin.template:
        src: hosts-file-entries.j2
        dest: /root/jinja-example-01.txt
