---
- name: Install remote facts
  hosts: web
  vars:
     remote_dir: /etc/ansible/facts.d
     #facts_file: custom.fact
     facts_file: chandra.fact
  tasks:
   - name: Create the remote directory
     ansible.builtin.file:
       path: "{{ remote_dir }}"
       state: directory
       recurse: yes

   - name: Install the new facts
     ansible.builtin.copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"
