---
- name: Display facts variable 
  hosts: web
  #gather_facts: false 
  tasks:
     - name: Display task-01 
       ansible.builtin.debug:
            msg: |
              "OS distrribution -  {{ ansible_distribution }}
               OS major version - {{ ansible_distribution_major_version}}"

     - name: Display task-02
       ansible.builtin.debug:
            msg: "MAC Address -  {{ ansible_default_ipv4.macaddress }}" 
 
