---
- name: root password reset 
  hosts: all
  vars_files:
     - root_pass.yml 
  tasks:
     - name: Reset root password - after 90 days 
       ansible.builtin.user:
           name: root 
           password: "{{ pass_var | password_hash('sha512')}}"
           #password: "{{ pass_var | password_hash('sha256')}}"
           #password: "{{'redhat' | password_hash('sha512')}}"
           update_password: always 
