---
- name: User & Group addition - 1st play 
  hosts: prod 
  tasks: 
     - name: Group Create - task-01 
       ansible.builtin.group:
          name: unixadm 
          state: present 
          gid: 776655

     - name: User Create - task-02
       ansible.builtin.user:
          name: user1 
          state: present 
          group: unixadm 
          uid: 44556
