---
- name: INstall apache deployment - 1st play 
  hosts: prod 
  vars:
    - apache_pkg: httpd
    - apache_svc: httpd
    - firewall_pkg: firewalld
    - firewall_svc: firewalld 
    - firewall_rules: http
  tasks:
    - name: "Install apache packages {{ apache_pkg }}"
      ansible.builtin.dnf:
         name: "{{ apache_pkg }}"
         state: present 

    - name: "Start & Enable apache server - {{ apache_svc}}"
      ansible.builtin.service:
         name: "{{ apache_svc }}"
         state: started 
         enabled: yes 

    - name: "Install firewalld packages {{ firewall_pkg }}"
      ansible.builtin.dnf:
         name: "{{ firewall_pkg }}"
         state: present 

    - name: "Start & Enable firewall server - {{ firewall_svc}}"
      ansible.builtin.service:
         name: "{{ firewall_svc }}"
         state: started 
         enabled: yes 

    - name: "Adding firewalld rules - {{firewall_rules }}"
      ansible.posix.firewalld:
         service: "{{ firewall_rules }}"
         immediate: yes
         permanent: yes
         state: enabled
 
    - name: Deploy application - index.html
      ansible.builtin.copy:
         content: "This is my web server - {{ inventory_hostname }} -- variable concepts   \n"
         dest: /var/www/html/index.html
          
...
