---
- name: My play - 1st-play 
  hosts: prod 
  tasks:
      - name: Install apache 
        ansible.builtin.yum:
          name: httpd
          state: present 

      - name: Start service httpd, if not started
        ansible.builtin.service:
          name: httpd
          state: started
          enabled: yes
  
