---
- name: Dictionary as input to loop 
  hosts: test
  vars_files:
    - mydetails.yml

  tasks:
    - name: Create Groups 
      ansible.builtin.group:
         name: "{{ item }}"
         state: present 
      loop: "{{ group_list }}"
      ## Passing list to loop

    - name: Adding users as per requirment.
      ansible.builtin.user:
         name: "{{ item.user_name }}"
         state: present
         groups: "{{ item.group_name }}"
         uid: "{{ item.uid_no }}"
         password: "{{ 'redhat' | password_hash('sha512') }}"
      loop: "{{ users_detail }}"

