---
- name: Register loop example
  hosts: dev 
  tasks:
    - name: DIsplay 
      ansible.builtin.shell: "echo 'This is my count - {{ item }}'"
      loop:
         - one 
         - two 
      register: echo_output_var

    - name: Print 
      ansible.builtin.debug:
         var: echo_output_var

    - name: Print2
      ansible.builtin.debug:
         msg: echo_output_var.rc
